### ISSUE TITLE
Make export transaction sets smoother

### ISSUE THREAD

**Issue by AquiburRKhan** [rehive/dashboard-angular#153]
Downloading transaction sets is not smooth and refreshes too many times.

**Comment by Cupofassam** [comment]
Testing this out - it's not refreshing all the time which is good :)

I'm not seeing a green dot ever though. When there is a red dot I open it to look at progress. It's not done, so I close it. Then the red dot disappears but I never see a green dot to indicate it's done and I haven't looked. Seems to be a bug where it knows I have looked at it, but it doesn't know I haven't looked at it since it finished generating.

Also the progress never changes from 0%. It's either 0% or the file is there for download.

**Comment by AquiburRKhan** [comment]
Joshua told me if there are multiple files only then it shows a percentage , if its one file being generated then it will go from 0 to 100%

**Comment by Cupofassam** [comment]
ok cool that's fine

The green dot is now working properly.

I have some trouble initially identifying my file - could we highlight the row of the any unseen transactions? In like al ight green colour.

**Comment by Cupofassam** [comment]
👍

**Comment by Cupofassam** [comment]
You know this is really small but can we make it so that when a user mouses over the new export download, the green fades away a bit rather than just disappearing?
