### ISSUE TITLE
Product Service UI

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#237]
Hey Aquib :)

Please create the UI for the product service!

Fields:

```    name 
    description
    value 
    currency 
    quantity 
    cost_price 
    product_type
    code 
```
UI:

Trying out a new thing here - for the ... menu please make it have a round circle - same colour as the new button, same hover effect. 

![product ui v1](https://user-images.githubusercontent.com/22153546/45633384-edfac080-ba9f-11e8-8f2a-20a77d1e7177.png)

Shout if you have any questions.

**Comment by AquiburRKhan** [comment]
Hey sam, 
Added the cost price as a column.

That error is showing because stephan needs to import the currency object instead of just the currency code  as the values need to be treated like currencies like it is in Rehive core, I talked to stephan about this before , so when he fixes this, I can proceed with further testing of the api

**Comment by AquiburRKhan** [comment]
Stephan made the changes to the product service as requested
Stephan also changed some of the fields, only some of them are required
name, value and currency
