### ISSUE TITLE
Product service

### ISSUE THREAD

**Issue by AquiburRKhan** [rehive/dashboard-angular#363]
Hey AQ :) Product Service changes!

Please do the Products changes first, then the Orders ones. The Orders CRUD is not as important (well, the view is, but we don't need create, edit, update initially) and can be added later.

- [x] 1. I noticed that when adding a new product or looking at the product listing page the page title says "Rewards service", please fix.

- [x] 2. Here is the design for Create and Edit Product:

![image](https://user-images.githubusercontent.com/22153546/51606035-7212f800-1f19-11e9-8cb8-a4716410d929.png)

For the prices field, there will be a currency drop down selector and an amount that corresponds with it. Users can click the + button next to amount to add another row.

No fields are required.

- [x] 3. Product list view: 

![image](https://user-images.githubusercontent.com/22153546/51606199-ecdc1300-1f19-11e9-81c4-3ca41f68f391.png)

The main difference here is removing of some fields and adding the Enabled field. I want to be able to disable/enable from this view (but if that is a huge pain leave it for last). In future maybe we can add columns to show currencies and prices but don't bother now. You can probably remove the columns button.

- [x] 4. Individual Product view:

![image](https://user-images.githubusercontent.com/22153546/51607495-78a36e80-1f1d-11e9-8009-fa57552206f0.png)

- [x] 5. Order create:

![image](https://user-images.githubusercontent.com/22153546/51606261-18f79400-1f1a-11e9-9a8f-6fb1e86fa8c5.png)

Users will be able to search a user, select a currency and can then add products and state the quantity of each.

- [x] 6. Order list view:

![image](https://user-images.githubusercontent.com/22153546/51606312-3a588000-1f1a-11e9-9702-4ec7eebc127d.png)

No need for columns button here either.

 - [x] 7. Individual order view with no payment info (pending and failed orders which were not complete at any point)

![image](https://user-images.githubusercontent.com/22153546/51606379-71c72c80-1f1a-11e9-8127-7589bb13a1d9.png)

- [x] 8. Individual order view with payment info (completed orders)

![image](https://user-images.githubusercontent.com/22153546/51606423-93281880-1f1a-11e9-9fb7-77feaf344eb2.png)

**Comment by Cupofassam** [comment]
Hey AQ, here are the filters:

**Product:**

`id`, `name`, `quantity`, `type`, `code`, `enabled`

**Orders:**

`id`, `user`, `status`, `currency`, `total_price`

**Comment by Cupofassam** [comment]
Hey AQ, thank you for pushing on this :) My feedback:

- [ ] 1. On product create/edit, can we have the + button initially next to the Prices field name when there are no prices? I kinda missed it on the other end of the page there:

![image](https://user-images.githubusercontent.com/22153546/51922494-d2120e80-23f1-11e9-848e-308641473774.png)

- [ ] 2. On product view, it seems that the enabled button is aligned with the top of the enabled field rather than aligned middle. If you looks, there is more space above the checkbox compared to underneath. Please align it to the middle of the field name:

![image](https://user-images.githubusercontent.com/22153546/51922800-6e3c1580-23f2-11e9-89f0-3ff5ebb57ddc.png)

- [ ] 3. When editing a product and I add a new price, when I have 2 prices added it inserts the new price between the 3 already added prices, which is a bit weird. Can you make it add after the already added prices? I think it is ordering the prices by alphabetical, but its order can just be as the user added them.

![image](https://user-images.githubusercontent.com/22153546/51922989-bfe4a000-23f2-11e9-8f04-1d1912570447.png)

- [ ] 4. When editing/creating a product, can we have the Prices section with the Prices heading in bold and then the currency and amount headings beneath? The + button to add a price can still go next to the Prices heading I think.

Josh is going to deploy this so long, cause this feedback is not anything breaking.

**Comment by Cupofassam** [comment]
I have merged this to master

**Comment by Cupofassam** [comment]
- [ ] 1. I think for prices the currency and amount fields are just too long.. I think reduce the currency selector by half and the amount one by 2/3rds.

I find it ab it odd that the + sign moves to the right after being next to prices, but I want to see how clicking it feels after we shorten the input fields.

- [x] 2. This is good

- [x] 3. Working well

- [ ] 4. Please make the Prices text colour be black

- [x] 5. Our fix works 👍 

New issue:

- [ ] 6. Creating a product and viewing a product seems quite slow, I see it's still calling the company's currencies page sometimes after I create a product.

**Comment by Cupofassam** [comment]
Yes please to re positioning '+' button :)

It's currently not letting me add a product with a blank description. I need to chat to @OdinsPlasmaRifle about whether we need to change stuff on Dashboard or if he will change it his side on Platform. Will update ASAP.

**Comment by Cupofassam** [comment]
Thanks M :) Looks good!

2 more things I want to add:

1. When no Prices have been added please hide the `Currency` and `Amount` fields until a user has clicked + to add a price.

2. When I have a price selected in a dropdown, please hide/disable it in any subsequent price drop downs, so I can only select a currency for a price once.

This is just a random question - I had a ton of currencies in my company. Whenever I create a new price it's always in USD, do you know why? Not really an issue just curious

**Comment by Cupofassam** [comment]
👍 perfect

Last change (I think!) - when adding a price, don't prefill the amount field with any number, just leave it blank

**Comment by Cupofassam** [comment]
Just checked out the orders functionality. Feedback there:

**Create order**

- [ ] 1. The field says "Currencies" but it should be "Currency"
- [ ] 2. Put the + button next to the Products field
- [ ] 3. Hide the Qty field until one product has been added
- [ ] 4. Don't prefill the Qty text field with anything

**Comment by Cupofassam** [comment]
👌
