### ISSUE TITLE
Missing font on production

### ISSUE THREAD

**Issue by Cupofassam** [rehive/dashboard-angular#410]
Hey M

Still seems we have a missing font on production. I see this error in Console:

`GET https://dashboard.rehive.com/MyFontsWebfontsKit.css net::ERR_ABORTED 404`
`dashboard.rehive.com/:17`

Network error is getting a 404 when trying to call this url: `https://dashboard.rehive.com/MyFontsWebfontsKit.css`

Please investigate why this file might be missing. It could be an issue with the build and you can't find why it's not loading please ping Michial on Slack.

**Comment by Cupofassam** [comment]
@michailbrynard Hey Michail, seems this bug on Dashboard is still present. Manosh implemented a fix to inject the file but it still doesn't seem to be being uploaded to production (it works on local). Is it perhaps to do with the build when deploying?

**Comment by michailbrynard** [comment]
@Dblaze47 @Cupofassam I'm not the best person to ask about css issues. I see that when I run `gulp build` locally, there is no MyFontsWebfontsKit.css in release folder. This is probably because of the way the gulp build script is set up to handle css files.

All the rest of the project is sass, could we not maybe port the few lines from MyFontsWebfontsKit.css over to the existing sass files?

**Comment by michailbrynard** [comment]
Not sure if this helps or if it is even the right type of thing, but I see someone wrote a mixin here https://gist.github.com/jonathantneal/d0460e5c2d5d7f9bc5e6
